[package]
name = "miaou-builder"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "cargo"] }
clap-help = "1.3"
cli-log = "2.1"
glob = "0.3"
grass = "0.13"
lazy-regex = "3.3"
